common: &common
  connection_string: <%= ENV.fetch('RAILS_COUCHBASE_CONNECTION_STRING') %>
  username: <%= ENV.fetch('RAILS_COUCHBASE_USERNAME') %>
  password: <%= ENV.fetch('RAILS_COUCHBASE_PASSWORD') %>
  bucket: <%= ENV.fetch('COUCHBASE_DEFAULT_BUCKET') %>

development:
  <<: *common

test:
  <<: *common

production:
  <<: *common