name: Test Couchbase connection

on: [workflow_dispatch]
defaults:
  run:
    shell: cbsh --script {0}

env:
  COUCHBASE_DEFAULT_BUCKET:  rails_${{ vars.COUCHBASE_DEFAULT_BUCKET }}
  COUCHBASE_DEFAULT_SCOPE:  ${{ github.head_ref || github.ref_name }}_${{ vars.COUCHBASE_DEFAULT_SCOPE }}
  COUCHBASE_DEFAULT_COLLECTION:  ${{ vars.COUCHBASE_DEFAULT_COLLECTION || '_default' }}
  RAILS_COUCHBASE_CONNECTION_STRING: ${{ secrets.COUCHBASE_CONNECTION_STRING }}
  RAILS_COUCHBASE_USERNAME: ${{ secrets.COUCHBASE_USERNAME }}
  RAILS_COUCHBASE_PASSWORD: ${{ secrets.COUCHBASE_PASSWORD }}
  COUCHBASE_USE_CAPELLA: ${{ vars.COUCHBASE_USE_CAPELLA || false }}
  COUCHBASE_OTLP_ENABLED: ${{ vars.COUCHBASE_OTLP_ENABLED || false }}

jobs:
  setup:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout ${{ github.event.repository.name }}
      uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - uses: ldoguin/setup-cbsh@develop
      with:
        version: 'nightly'
        branch: 'main'
        enable-plugins: ''
        config:  ${{ secrets.CBSHELL_CONFIG }}
    - name: Setup Couchbase Bucket, Scope, Collection
      run: |
          source ${{ github.workspace }}/scripts/dbSetup.nu
          dbSetup $env.COUCHBASE_DEFAULT_BUCKET $env.COUCHBASE_DEFAULT_SCOPE $env.COUCHBASE_DEFAULT_COLLECTION
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.4
        bundler-cache: true
    - name: Run tests
      env:
        RAILS_ENV: test
        RAILS_COUCHBASE_CONNECTION_STRING: ${{ secrets.COUCHBASE_CONNECTION_STRING }}
        COUCHBASE_DEFAULT_BUCKET: ${{ secrets.COUCHBASE_DEFAULT_BUCKET }}
        RAILS_COUCHBASE_USERNAME: ${{ secrets.COUCHBASE_USERNAME }}
        RAILS_COUCHBASE_PASSWORD: ${{ secrets.COUCHBASE_PASSWORD }}
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Tear Down Bucket
      run: |
        cb-env bucket $env.COUCHBASE_DEFAULT_BUCKET
        scopes drop $env.COUCHBASE_DEFAULT_SCOPE